name: Build and Deploy Code

on: 
  push: 
    branches: ['main'] 
  pull_request:
    branches: ['main']

jobs:
  job1:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: talib
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: talib
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f70f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 100

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: talib
          POSTGRES_DB: fastapi_test
          # POSTGRES_USER: talib
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest

    
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4  # Updated to the latest version (v4)

      - name: Install Python
        uses: actions/setup-python@v4  # Corrected to v4
        with:
          python-version: "3.10"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies 
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          pip install pytest
          pytest
